config/routes.rb
Creations::Application.routes.draw do

scope "/:locale", locale: /en|ru|cs/ do
    
  resources :users, only: [:new, :create, :destroy] 
  resources :photos
  resources :post_categories, :path => "categories"

  resources :works do
    resources :posts
  end  
end

scope "(:locale)", locale: /en|ru|cs/ do 

  root :to => 'welcome#index'

  resources :sessions, only: [:new, :create, :destroy]

  get '/sign_in' => 'sessions#new'
  match '/sign_out' => 'sessions#destroy', via: :delete

  get '/contact' => 'welcome#contact'
  get '/about' => 'welcome#about'

  get '/admin' => "admin#admin"
  get '/admin/categories' => "admin#admin_categories"
  get '/admin/works' => "admin#admin_works"
  get '/admin/posts' => "admin#admin_posts"
  get '/admin/users' => "admin#admin_users"

end  

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  
   validates :title, presence: true
   validates :description, presence: true
   validates :annotation, presence: true
   
   has_many :photos, :dependent => :destroy
   belongs_to :work

   accepts_nested_attributes_for :photos, :allow_destroy => true

   before_save { |post| post.industry = industry.upcase }
   before_save { |post| post.task = task.upcase }

   scope :recent, -> { order("created_at desc").limit(4) }
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base

  translates :name

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }
  validates :password_confirmation, presence: true

end

app/models/work.rb
class Work < ActiveRecord::Base
 
  has_many :posts, :dependent => :destroy

  scope :latest, -> { Post.recent }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :signed_in_user

  layout "admin"

  def admin
  end

  def admin_categories
    @post_categories = PostCategory.all
  end

  def admin_works
    @works = Work.all
  end

  def admin_posts
    @posts = Post.all
    @works = Work.all
  end

  def admin_users
    @users = User.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_filter :signed_in_user, only: [:edit, :update, :create, :new, :destroy ]
  
  def new
    @post = Post.find(params[:post_id])
    @photo = @post.photos.build
  end

  def create
    @post = Post.find(params[:post_id])
    @photo = @post.photos.build(photo_params)
    if @photo.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.photos.find(params[:id]).destroy
    redirect_to @post
  end

  private 

  def photo_params
    params.require(:photo).permit!
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :create, :new, :destroy ]
  layout :resolve_layout

  def new
    @work = Work.find(params[:work_id])
    @post = @work.posts.build
  end

  def create
    @work = Work.find(params[:work_id])
    @post = @work.posts.build(post_params)
    if @post.save
      redirect_to "/admin/posts"
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @work = Work.find(params[:work_id])
    @post = @work.posts.find(params[:id])
  end

  def edit
    @work = Work.find(params[:work_id])
    @post = @work.posts.find(params[:id])
  end

  def update
    @work = Work.find(params[:work_id])
    @post = @work.posts.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to "/admin/posts"
    else
      render 'edit'
    end
  end 

  def destroy
    @work = Work.find(params[:work_id])
    @work.posts.find(params[:id]).destroy
    redirect_to "/admin/posts"
  end

  private

    def resolve_layout
      case action_name
      when "new", "create", "edit"
        "admin"
      else
        "application"
      end
    end

    def post_params
      params.require(:post).permit!
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user
  layout "admin"

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to "/admin/users"
    else
      render 'new' 
    end   
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to "/admin/users"   
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.recent
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :create, :new, :destroy, :show ]
  layout :resolve_layout

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to "/admin/works"
    else
      render 'new'
    end
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update_attributes(work_params)
      redirect_to "/admin/works"
    else
      render 'edit'
    end
  end

  def destroy
    @work = Work.find(params[:id]).destroy
    redirect_to "/admin/works"
  end

  def show
    @work = Work.find(params[:id])
  end

  def index
    @works = Work.all
    @post_categories = PostCategory.all
  end

  private

    def resolve_layout
      case action_name
      when "new", "create", "edit", "show"
        "admin"
      else
        "application"
      end
    end

    def work_params
      params.require(:work).permit(:name, :post_ids => [])  
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Web studio Mighty Creations"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'nav-active' : 'nav-nonactive'

    if current_page?(link_path)
      content_tag(:li, :class => class_name ) do
        link_text
      end
    else          
      content_tag(:li, :class => class_name) do
        link_to link_text, link_path
      end
    end
  end

  def set_human_locale(locale)
    case locale
    when :cs || "cs"
      "Czech"
    when :ru || "ru"
      "Russian"
    when :en || "en"
      "English"  
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    redirect_to sign_in_url, notice: "Please sign in." unless signed_in? 
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/admin.html.erb
<% provide(:title, "Administration") %>

<section id="admin-title">
  <h1>Administration</h1>
</section>

<section id="admin-container">

  <section id="admin-inner-container">
    <h2><%= link_to "Manage post categories", "/admin/categories" %></h2>
    <h2><%= link_to "Manage works", "/admin/works" %></h2>
    <h2><%= link_to "Manage posts", "/admin/posts" %></h2>
    <h2><%= link_to "Manage users", "/admin/users" %></h2>  
  </section>

</section>

app/views/admin/admin_categories.html.erb
<% provide(:title, "Administration - Post categories") %>

<section id="admin-post-categories-container">
  <h1>All category names</h1>
  <table>
    <h4><%= link_to "create new item category", new_post_category_path, :class => "create-link" %></h4>
    <% @post_categories.each do |post_category| %>
      <tr>
        <td><%= post_category.name %></td>
        <td><%= link_to "edit", edit_post_category_path(post_category) %></td>
        <td><%= link_to "delete", post_category_path(post_category), method: :delete, data: { confirm: "You sure?" } %></td> 
    </tr>
    <% end %>
  </table>
</section>

app/views/admin/admin_posts.html.erb
<% provide(:title, "Administration - Posts") %>

<section id="admin-posts-container">
  <h1>All posts</h1>
  <% @works.each do |work| %>
    <h2><%= work.name %></h2>
    <h4><%= link_to "add post to work", new_work_post_path(work), :class => "create-link" %></h4>
    <table>
      <tr>
        <th>Post name</th>
        <th>Post subtitle</th>
        <th>Post category</th>
      </tr>    
      <% work.posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.subtitle %></td>
          <td><%= post.post_category  %></td>
          <td><%= link_to 'show',  work_post_path(work, post) %></td>
          <td><%= link_to 'edit',  edit_work_post_path(work, post) %></td>
          <td><%= link_to 'delete', work_post_path(work, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
  <% end %>    
</section>

app/views/admin/admin_users.html.erb
<% provide(:title, "Administration - Users") %>

<section id="admin-users-container">
  <h1>All users</h1>
  <table>
    <h4><%= link_to "create new user", new_user_path, :class => "create-link" %></h4>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to "delete", user_path(user), method: :delete, data: { confirm: "You sure?" } %></td> 
    </tr>
    <% end %>
  </table>
</section>

app/views/admin/admin_works.html.erb
<% provide(:title, "Administration - Works") %>

<section id="admin-works-container">
  <h1>All works</h1>
  <table>
    <h4><%= link_to "create new work", new_work_path, :class => "create-link" %></h4>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.name %></td>
        <td><%= link_to "edit", edit_work_path(work) %></td>
        <td><%= link_to "delete", work_path(work), method: :delete, data: { confirm: "You sure?" } %></td> 
    </tr>
    <% end %>
  </table>
</section>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "nested_form" %>
  <%= javascript_include_tag "hover" %>
  <%= javascript_include_tag "lang" %>
  <%= csrf_meta_tags %>
 
</head>

<body>
  <% if signed_in? %>
    <nav id="admin-navigation">
      <section id="admin-pages">
        <% unless current_page?("/admin") %>
        <ul>
          <li><%= link_to "Admin page", "/admin" %></li>
          <li><%= link_to "Post categories", "/admin/categories" %></li>
          <li><%= link_to "Works", "/admin/works" %></li>
          <li><%= link_to "Posts", "/admin/posts" %></li>
          <li><%= link_to "Users", "/admin/users" %></li>
        </ul>
        <% end %>
      </section>
      <section id="admin-actions">        
        <ul>
          <li><%= link_to "sign out", sign_out_path, method: 'delete' %></li>
          <li><%= link_to "home", root_url %></li>
          <% unless current_page?("/admin") %>
            <li><%= link_to "main admin", "/admin" %></li>
          <% end %>
        </ul>        
      </section>
      <section id="admin-cleaner"></section>
    </nav>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "nested_form" %>
  <%= javascript_include_tag "hover" %>
  <%= javascript_include_tag "lang" %>
  <%= csrf_meta_tags %>
 
</head>
<body class="bg_image1">
  <%= render partial: "shared/header" %>  
  
  <%= yield %>

  <%= render partial: "shared/socials" %>
  <%= render partial: "shared/footer" %>

</body>
</html>

app/views/shared/_about_top_picture.html.erb
<div id="top-pic">
  <section id="sec">
    <div class="wrap">
      <div class="box colour1">
        <div class="contacts_text_bold"><%= I18n.t(:about_top_pic_title) %></div>
        <p><%= I18n.t(:about_top_pic_text_1) %></p>
        <p><%= I18n.t(:about_top_pic_text_2) %></p>
      </div>
    </div>
    <div class="clear"></div>
  </section>
</div>

app/views/shared/_add_translations.html.erb
<h4>Form is for <%= set_human_locale(I18n.locale) %> language.
  Add translations:
  <% I18n.available_locales.each do |locale| %>
    <% unless locale == I18n.locale %>
      <%= link_to set_human_locale(locale), {:locale => locale} %>  
    <% end %>
	<% end %>
</h4>

app/views/shared/_contact_top_picture.html.erb
<div id="top-pic">
	<section id="sec">
		<div class="wrap">
			<div class="box colour1">
				<div class="contacts_text_bold"><%= I18n.t(:contact_top_pic_title) %></div>
				<p><%= I18n.t(:contact_top_pic_text_1) %></p>
				<p><%= I18n.t(:contact_top_pic_text_2) %></p>
			</div>
		</div>
		<div class="clear"></div>
	</section>
</div>

app/views/shared/_footer.html.erb
<section id="footer">
  <div class="wrap">
    <h3><%= I18n.t(:contact_us) %></h3>
    <table id="footer-table">
      <tr>
        <th><%= I18n.t(:address) %></th>
        <th><%= I18n.t(:telephone) %></th>
        <th><%= I18n.t(:email) %></th>
      </tr>
      <tr class="footer-fonts">
        <td>Legerova 39/1490 12000<br>Praha 2, Czech republic</td>
        <td>+420 775 500 447</td>
        <td><a href="mailto:mighty@creations.cz">mighty@creations.cz<a></td>
      </tr>
    </table>
  </div>
</section>

app/views/shared/_header.html.erb
<section id="header">
  <div class="logo">
    <%= link_to (image_tag ("mc_logo.png")), root_path %>
  </div>
  <div class="top_space"><p class="top_label"><%= I18n.t(:greeting) %></p>
    
  </div>

  <div id="nav">
    <nav class="site_navigation">
      <ul>
        <%= nav_link I18n.t(:menu_works), works_path %>
        <%= nav_link I18n.t(:menu_about), "/about" %>
        <%= nav_link I18n.t(:menu_contact), "/contact" %>
      </ul>
    </nav>
    <ul id="jmenu">
      <li><%= I18n.locale %>
        <ul class="secondary-jmenu"> 
          <% I18n.available_locales.each do |loc| %>
            <% unless I18n.locale == loc  %>
              <li><%= link_to "#{loc.upcase}", :locale => loc %></li>
            <% end %>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>

  <div id="all-signout">
    <% if signed_in? %>
      <%= link_to "sign out", sign_out_path, method: 'delete' %>  |
      <%= link_to "admin", "/admin" %>
    <% end %>
  </div>
</section>

app/views/shared/_main_top_picture.html.erb
<div id="top-pic">
  <section id="sec">
    <div class="wrap">
      <div class="box colour1">
        <div class="contacts_text_bold"><%= I18n.t(:main_top_pic_title) %></div>
        <p><%= I18n.t(:main_top_pic_text_1) %></p>
        <p><%= I18n.t(:main_top_pic_text_2) %></p>
      </div>
    </div>
    <div class="clear"></div>
  </section>
</div>

app/views/shared/_socials.html.erb
<section id="soc-nets">
  <p id="soc-text"><%= I18n.t(:friendship)%></p>
  <div id="soc-icons">
    <a href="#" class="soc-link"><%= image_tag "fb_icon.png", :mouseover => "fb_icon_hover.png" %></a>
    <a href="#" class="soc-link"><%= image_tag "dribbble_icon.png", :mouseover => "dribbble_icon_hover.png" %></a>
    <a href="#" class="soc-link"><%= image_tag "inst_icon.png", :mouseover => "inst_icon_hover.png" %></a>
    <a href="#" class="soc-link"><%= image_tag "tw_icon.png", :mouseover => "tw_icon_hover.png" %></a>
  </div>
</section>

app/views/shared/_top_picture.html.erb
<div id="top-pic">
	<section id="sec">
		<div class="wrap">
			<div class="box colour1">
				<h1><%= I18n.t(:top_pic_title) %></h1>
				<p><%= I18n.t(:top_pic_text_1) %></p>
				<p><%= I18n.t(:top_pic_text_2) %></p>
			</div>
		</div>
		<div class="clear"></div>
	</section>
</div>

app/views/shared/_work_top_picture.html.erb
<div id="top-pic">
  <section id="sec">
    <div class="wrap">
      <div class="box colour1">
        <div class="contacts_text_bold"><%= I18n.t(:work_top_pic_title) %></div>
        <p><%= I18n.t(:work_top_pic_text_1) %></p>
        <p><%= I18n.t(:work_top_pic_text_2) %></p>
      </div>
    </div>
    <div class="clear"></div>
  </section>
</div>